[
   {
      "partido":"PP",
      "mediaAutoubicacion":7.09,
      "votantes":2509,
      "nsnc":302
   },
   {
      "partido":"PSOE",
      "mediaAutoubicacion":3.81,
      "votantes":2330,
      "nsnc":260
   },
   {
      "partido":"No votaría",
      "mediaAutoubicacion":4.62,
      "votantes":760,
      "nsnc":638
   },
   {
      "partido":"No sabe todavía",
      "mediaAutoubicacion":4.59,
      "votantes":2541,
      "nsnc":786
   },
   {
      "partido":"N.C.",
      "mediaAutoubicacion":4.75,
      "votantes":733,
      "nsnc":340
   }
]